"""Maintained hash API subset for locked crc8 0.2.1; no native runtime stub."""

from typing import Self

class crc8:
    def __init__(self, initial_string: bytes = b"", initial_start: int = 0) -> None: ...
    def update(self, bytes_: bytes) -> Self: ...
    def digest(self) -> bytes: ...
