import React, { act } from 'react';
import { createRoot } from 'react-dom/client';
import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import ProjectTree from './ProjectTree';
import { useStore } from '../store';
let root, container;
const original = useStore.getState();
beforeEach(() => { globalThis.IS_REACT_ACT_ENVIRONMENT = true; container = document.createElement('div'); document.body.append(container); root = createRoot(container); });
afterEach(async () => { await act(() => root.unmount()); container.remove(); useStore.setState(original, true); });
test('tree owns named nested rows and supports roving navigation without activating nested actions', async () => {
  const loadProject = vi.fn();
  useStore.setState({ projects: [{ id: 1, name: 'Child', category_id: 1 }, { id: 2, name: 'Root' }], categories: [{ id: 1, name: 'Folder' }], loadProject });
  await act(() => root.render(<ProjectTree />));
  const rows = () => [...container.querySelectorAll('[role=treeitem]')];
  const key = async (element, value) => act(() => element.dispatchEvent(new KeyboardEvent('keydown', { key: value, bubbles: true, cancelable: true })));
  expect(container.querySelector('[role=tree]').getAttribute('aria-label')).toBe('Saved projects and folders');
  expect(rows().map(row => row.tabIndex)).toEqual([0, -1]);
  await key(rows()[0], 'ArrowRight');
  expect(document.getElementById(rows()[0].getAttribute('aria-owns')).getAttribute('role')).toBe('group');
  await key(rows()[0], 'ArrowRight');
  expect(document.activeElement).toBe(rows()[1]);
  expect(rows().filter(row => row.tabIndex === 0)).toEqual([rows()[1]]);
  await key(rows()[1], 'ArrowLeft'); expect(document.activeElement).toBe(rows()[0]);
  await key(rows()[0], 'End'); expect(document.activeElement).toBe(rows()[2]);
  await key(rows()[2].querySelector('button'), 'Enter'); expect(loadProject).not.toHaveBeenCalled();
  await key(rows()[2], 'Enter'); expect(loadProject).toHaveBeenCalledOnce();
  await act(() => useStore.setState({ projects: [{ id: 1, name: 'Child', category_id: 1 }] }));
  expect(rows()[0].tabIndex).toBe(0);
});
