#!/bin/sh
set -eu
app_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)
case "${XDG_DATA_HOME:-}" in
    /*) data_home=$XDG_DATA_HOME ;;
    *) data_home=${HOME:?HOME is required}/.local/share ;;
esac
exec "$app_dir/usr/bin/CatLabel-Launcher" --installation-root "$data_home/catlabel" "$@"
