"""Maintained subset of the pypdfium2 helper API used by CatLabel.

Signatures follow the installed helpers (document.py, page.py, bitmap.py).
Extend this stub when adding another PDFium operation; do not silence imports.
"""

from pathlib import Path
from typing import BinaryIO

from PIL.Image import Image

class PdfBitmap:
    def to_pil(self) -> Image: ...
    def close(self) -> None: ...

class PdfPage:
    def get_size(self) -> tuple[float, float]: ...
    def render(self, scale: float = 1) -> PdfBitmap: ...
    def close(self) -> None: ...

class PdfDocument:
    def __init__(self, input: bytes | str | Path) -> None: ...
    @classmethod
    def new(cls) -> PdfDocument: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> PdfPage: ...
    def new_page(self, width: float, height: float, index: int | None = None) -> PdfPage: ...
    def save(self, dest: BinaryIO, version: int | None = None, flags: int = 0) -> None: ...
    def close(self) -> None: ...
