from __future__ import annotations

from collections.abc import Awaitable
from enum import IntFlag

class IInputStream: ...
class IOutputStream: ...

class InputStreamOptions(IntFlag):
    NONE = 0
    PARTIAL = 1
    READ_AHEAD = 2

class DataReader:
    input_stream_options: InputStreamOptions

    def __init__(self, input_stream: IInputStream | None) -> None: ...
    def load_async(self, count: int, /) -> Awaitable[int]: ...
    def read_bytes(self, value: bytearray, /) -> None: ...
    def close(self) -> None: ...

class DataWriter:
    def __init__(self, output_stream: IOutputStream | None = None) -> None: ...
    def write_bytes(self, value: bytearray, /) -> None: ...
    def store_async(self) -> Awaitable[int]: ...
    def flush_async(self) -> Awaitable[bool]: ...
    def close(self) -> None: ...
