"""Generate the checked-in canvas/edit schemas and frontend document types."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from catlabel.services.documents import CanvasDocument, EditOperation

ROOT = Path(__file__).resolve().parents[1]


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(part) for part in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if kind == "object":
        return "Record<string, unknown>"
    if kind == "string" and schema.get("pattern"):
        return "`${number}%`"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(str(kind), "unknown")


def generate() -> dict[Path, str]:
    schema = CanvasDocument.model_json_schema()
    definitions = dict(schema.get("$defs", {}))
    root = schema.get("$ref", "").rsplit("/", 1)[-1]
    if not root:
        definitions["CanvasDocument"] = schema
    lines = ["// Generated by tools/sync_document_contract.py; do not edit.", ""]
    for name, definition in definitions.items():
        lines.append(f"export interface {name} {{")
        if definition.get("additionalProperties"):
            lines.append("  [key: string]: unknown;")
        required = set(definition.get("required", []))
        for key, value in definition.get("properties", {}).items():
            optional = "" if key in required else "?"
            lines.append(f"  {key}{optional}: {ts_type(value)};")
        lines.extend(["}", ""])
    return {
        ROOT / "catlabel/data/document.schema.json": json.dumps(schema, indent=2)
        + "\n",
        ROOT / "catlabel/data/edit-operation.schema.json": json.dumps(
            EditOperation.model_json_schema(), indent=2
        )
        + "\n",
        ROOT / "frontend/src/domain/generated/document.ts": "\n".join(lines),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    for path, content in generate().items():
        if arguments.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Document contract drift: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
