"""Generate pip and Pixi dependency files from ``pyproject.toml``."""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path
from typing import Any, cast

ROOT = Path(__file__).resolve().parents[1]
GENERATED_HEADER = "# Generated by tools/sync_dependencies.py; do not edit."
_NAME_PATTERN = re.compile(r"([A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?)(.*)\Z")
_SPECIFIER_PATTERN = re.compile(
    r"\s*(?:(?:===|==|!=|<=|>=|~=|<|>)\s*[A-Za-z0-9][A-Za-z0-9.!+_-]*"
    r"(?:\s*,\s*(?:===|==|!=|<=|>=|~=|<|>)\s*[A-Za-z0-9][A-Za-z0-9.!+_-]*)*)?\s*\Z"
)
_MARKER_PATTERN = re.compile(r"sys_platform\s*==\s*(['\"])(darwin|win32)\1\Z")
_NAME_NORMALIZATION_PATTERN = re.compile(r"[-_.]+")
PIXI_PLATFORMS = ("win-64", "linux-64", "linux-aarch64", "osx-64", "osx-arm64")
_MARKER_PLATFORMS = {
    "win32": ("win-64",),
    "darwin": ("osx-64", "osx-arm64"),
}
_RequirementEntry = tuple[str, str]


class DependencyManifestError(ValueError):
    """Raised when a requirement cannot be represented by the generated files."""


def _requirements(value: object, label: str) -> list[str]:
    if not isinstance(value, list):
        raise DependencyManifestError(
            f"{label} must be an array of requirement strings"
        )
    result: list[str] = []
    for requirement in cast(list[object], value):
        if not isinstance(requirement, str):
            raise DependencyManifestError(
                f"{label} must be an array of requirement strings"
            )
        result.append(requirement)
    return result


def _requirement_lists(
    pyproject: dict[str, Any],
) -> tuple[str, list[str], list[str], list[str], list[str]]:
    project = pyproject.get("project")
    if not isinstance(project, dict):
        raise DependencyManifestError("pyproject.toml must contain a [project] table")
    project = cast(dict[str, Any], project)

    project_name = project.get("name")
    if not isinstance(project_name, str) or not project_name.strip():
        raise DependencyManifestError("[project].name must be a non-empty string")

    base = _requirements(project.get("dependencies", []), "[project].dependencies")
    optional = project.get("optional-dependencies", {})
    if not isinstance(optional, dict):
        raise DependencyManifestError("[project.optional-dependencies] must be a table")
    optional = cast(dict[str, Any], optional)
    headless = _requirements(optional.get("headless", []), "headless")
    ai = _requirements(optional.get("ai", []), "ai")
    launcher = _requirements(optional.get("launcher", []), "launcher")

    return project_name, base, headless, ai, launcher


def _parse_requirement(requirement: str) -> tuple[str, str, str | None]:
    """Return normalized package name, version specifier, and supported marker."""
    if not requirement or requirement != requirement.strip():
        raise DependencyManifestError(
            f"requirement has surrounding whitespace: {requirement!r}"
        )

    pieces = requirement.split(";")
    if len(pieces) > 2:
        raise DependencyManifestError(
            f"unsupported requirement marker syntax: {requirement!r}"
        )

    raw_requirement = pieces[0].strip()
    if "[" in raw_requirement or "]" in raw_requirement or "@" in raw_requirement:
        raise DependencyManifestError(
            f"extras and direct references are unsupported: {requirement!r}"
        )

    match = _NAME_PATTERN.fullmatch(raw_requirement)
    if match is None:
        raise DependencyManifestError(
            f"unsupported requirement syntax: {requirement!r}"
        )

    raw_name, raw_specifier = match.groups()
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", raw_name):
        raise DependencyManifestError(f"unsupported package name: {requirement!r}")
    if not _SPECIFIER_PATTERN.fullmatch(raw_specifier):
        raise DependencyManifestError(f"unsupported version specifier: {requirement!r}")

    marker: str | None = None
    if len(pieces) == 2:
        raw_marker = pieces[1].strip()
        marker_match = _MARKER_PATTERN.fullmatch(raw_marker)
        if marker_match is None:
            raise DependencyManifestError(
                f"unsupported environment marker: {requirement!r}"
            )
        marker = marker_match.group(2)

    normalized_name = _NAME_NORMALIZATION_PATTERN.sub("-", raw_name).lower()
    return normalized_name, raw_specifier.strip(), marker


def _platform_entries(
    requirements: list[str], *, source: str
) -> tuple[list[_RequirementEntry], dict[str, list[_RequirementEntry]]]:
    """Resolve unmarked and supported platform-specific requirements."""
    common: list[_RequirementEntry] = []
    targets: dict[str, list[_RequirementEntry]] = {
        platform: [] for platform in PIXI_PLATFORMS
    }
    seen: dict[str, dict[str, str]] = {platform: {} for platform in PIXI_PLATFORMS}
    for requirement in requirements:
        name, specifier, marker = _parse_requirement(requirement)
        platforms = PIXI_PLATFORMS if marker is None else _MARKER_PLATFORMS[marker]
        if marker is None:
            common.append((name, specifier or "*"))
        else:
            for platform in platforms:
                targets[platform].append((name, specifier or "*"))

        for platform in platforms:
            prior = seen[platform].get(name)
            if prior is not None:
                raise DependencyManifestError(
                    f"{source} has overlapping requirements for normalized package "
                    f"{name!r} on {platform}: {prior!r} and {requirement!r}"
                )
            seen[platform][name] = requirement

    return common, targets


def _check_feature_overlaps(
    base: tuple[list[_RequirementEntry], dict[str, list[_RequirementEntry]]],
    headless: tuple[list[_RequirementEntry], dict[str, list[_RequirementEntry]]],
    ai: tuple[list[_RequirementEntry], dict[str, list[_RequirementEntry]]],
) -> None:
    feature_requirements = [
        ("[project].dependencies", base),
        ("headless", headless),
        ("ai", ai),
    ]
    for index, (left_name, (left_common, left_targets)) in enumerate(
        feature_requirements
    ):
        for right_name, (right_common, right_targets) in feature_requirements[
            index + 1 :
        ]:
            for platform in PIXI_PLATFORMS:
                left_names = {
                    name for name, _specifier in [*left_common, *left_targets[platform]]
                }
                right_names = {
                    name
                    for name, _specifier in [
                        *right_common,
                        *right_targets[platform],
                    ]
                }
                overlap = sorted(left_names & right_names)
                if overlap:
                    raise DependencyManifestError(
                        f"{left_name} and {right_name} have overlapping requirements "
                        f"for normalized package {overlap[0]!r} on {platform}"
                    )


def _render_requirements(requirements: list[str]) -> bytes:
    for requirement in requirements:
        _parse_requirement(requirement)
    lines = [GENERATED_HEADER, *requirements]
    return ("\n".join(lines) + "\n").encode("utf-8")


def _render_pixi(
    project_name: str,
    base_requirements: list[str],
    headless_requirements: list[str],
    ai_requirements: list[str],
) -> bytes:
    base_common, base_targets = _platform_entries(
        base_requirements,
        source="[project].dependencies",
    )
    headless_common, headless_targets = _platform_entries(
        headless_requirements,
        source="headless",
    )
    ai_common, ai_targets = _platform_entries(
        ai_requirements,
        source="ai",
    )
    _check_feature_overlaps(
        (base_common, base_targets),
        (headless_common, headless_targets),
        (ai_common, ai_targets),
    )

    lines = [
        GENERATED_HEADER,
        "",
        "[workspace]",
        f"name = {json.dumps(project_name)}",
        'channels = ["conda-forge"]',
        "platforms = ["
        + ", ".join(json.dumps(platform) for platform in PIXI_PLATFORMS)
        + "]",
        "",
        "[dependencies]",
        'python = "==3.11.15"',
        "",
        "[pypi-dependencies]",
    ]
    for name, specifier in base_common:
        lines.append(f"{name} = {json.dumps(specifier)}")
    for platform in PIXI_PLATFORMS:
        entries = base_targets[platform]
        if entries:
            lines.extend(["", f"[target.{platform}.pypi-dependencies]"])
            lines.extend(
                f"{name} = {json.dumps(specifier)}" for name, specifier in entries
            )

    for feature_name, common, targets in (
        ("headless", headless_common, headless_targets),
        ("ai", ai_common, ai_targets),
    ):
        lines.extend(["", f"[feature.{feature_name}.pypi-dependencies]"])
        lines.extend(f"{name} = {json.dumps(specifier)}" for name, specifier in common)
        for platform in PIXI_PLATFORMS:
            entries = targets[platform]
            if entries:
                lines.extend(
                    [
                        "",
                        f"[feature.{feature_name}.target.{platform}.pypi-dependencies]",
                    ]
                )
                lines.extend(
                    f"{name} = {json.dumps(specifier)}" for name, specifier in entries
                )
    lines.extend(
        [
            "",
            "[environments]",
            'headless = ["headless"]',
            'ai = ["ai"]',
            'ai-headless = ["ai", "headless"]',
            "",
            "[tasks]",
            'start = "python -m catlabel"',
            'test = "python -m unittest discover -s tests -v"',
            "",
        ]
    )
    return "\n".join(lines).encode("utf-8")


def expected_outputs(root: Path) -> dict[Path, bytes]:
    """Build expected generated-file contents without mutating the repository."""
    try:
        pyproject = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as error:
        raise DependencyManifestError(f"cannot read pyproject.toml: {error}") from error

    project_name, base, headless, ai, launcher = _requirement_lists(pyproject)
    return {
        root / "requirements.txt": _render_requirements(base),
        root / "requirements-ai.txt": _render_requirements(ai),
        root / "launcher-requirements.txt": _render_requirements(launcher),
        root / "pixi.toml": _render_pixi(project_name, base, headless, ai),
    }


def _check(outputs: dict[Path, bytes]) -> int:
    drifted: list[str] = []
    for path, expected in outputs.items():
        try:
            current = path.read_bytes()
        except OSError:
            drifted.append(path.name)
            continue
        if current != expected:
            drifted.append(path.name)

    if drifted:
        print(
            "generated dependency files are out of date: "
            + ", ".join(drifted)
            + " (run with --write)",
            file=sys.stderr,
        )
        return 1
    print("generated dependency files match pyproject.toml")
    return 0


def _write(outputs: dict[Path, bytes]) -> int:
    for path, content in outputs.items():
        path.write_bytes(content)
    print("generated " + ", ".join(path.name for path in outputs))
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check", action="store_true", help="fail if generated files have drifted"
    )
    mode.add_argument("--write", action="store_true", help="write generated files")
    parser.add_argument(
        "--root",
        type=Path,
        default=ROOT,
        help="project root (defaults to the repository containing this script)",
    )
    args = parser.parse_args(argv)

    try:
        outputs = expected_outputs(args.root)
    except DependencyManifestError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    if args.write:
        return _write(outputs)
    return _check(outputs)


if __name__ == "__main__":
    raise SystemExit(main())
